# Generated by Django 6.0.3 on 2026-05-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
