# Generated by Django 6.0.3 on 2026-05-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_expenses_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expenses',
            table='family_expenses',
        ),
    ]
